import React,{useEffect,useMemo,useRef,useState}from"react";import{createRoot}from"react-dom/client";import*as I from"lucide-react";import"./styles.css";
const API="http://localhost:8000";
const NAV=[["command","Command Center",I.Radar],["live","Live Detector",I.RadioTower],["repo","Repository X-Ray",I.GitBranch],["deps","Dependency DNA",I.PackageSearch],["secrets","Secret Sentinel",I.KeyRound],["behavior","Behavior Lab",I.Activity],["intel","Threat Intelligence",I.Globe2],["attack","Attack Path",I.Network],["trust","Provenance & Trust",I.Fingerprint],["sbom","SBOM Forge",I.FileJson],["cicd","CI/CD Guardian",I.GitPullRequest],["risk","Risk Simulator",I.SlidersHorizontal],["remediate","Remediation Center",I.Wrench],["evidence","Evidence Vault",I.Archive],["compliance","Compliance Matrix",I.BadgeCheck],["copilot","AI Security Copilot",I.BrainCircuit],["defense","Defense Autopilot",I.Bot]];
const STAGES=["INGEST","FINGERPRINT","DEPENDENCY DNA","SECRET SENTINEL","BEHAVIOR LAB","THREAT CORRELATION","ATTACK PATH","DEFENSE"];
function Badge({children,k=""}){return <span className={"badge "+k}>{children}</span>}
function App(){const[file,setFile]=useState(),[data,setData]=useState(),[busy,setBusy]=useState(false),[tab,setTab]=useState("command"),[stage,setStage]=useState(0),[logs,setLogs]=useState([]),ref=useRef();
useEffect(()=>{let t;if(busy){let n=0;t=setInterval(()=>{setStage(Math.min(n,7));setLogs(x=>[...x.slice(-8),`[${new Date().toLocaleTimeString()}] ${STAGES[n]||"DEFENSE"} :: analysis pulse`]);n++},520)}return()=>clearInterval(t)},[busy]);
async function scan(f){if(!f)return;setFile(f);setData(null);setBusy(true);try{let fd=new FormData();fd.append("file",f);let r=await fetch(API+"/api/scan",{method:"POST",body:fd});if(!r.ok)throw Error(await r.text());setData(await r.json());setStage(7)}catch(e){alert("Backend unavailable. Run FastAPI on port 8000.\\n\\n"+e.message)}finally{setBusy(false)}}
return <div className="app"><div className="stars"/><div className="grid"/><div className="beam"/><header><div className="brand"><div className="logo"><I.ShieldCheck/></div><div><b>AEGIS<span>FLOW</span> OMEGA</b><small>AUTONOMOUS SOFTWARE SUPPLY-CHAIN DEFENSE</small></div></div><div className="liveTop"><i/>SENTINEL NETWORK <strong>ONLINE</strong><em>DEFENSIVE MODE</em></div><button className="re" onClick={()=>file&&scan(file)}><I.RefreshCw/></button></header>
<div className="layout"><aside><div className="cap">OMEGA OPERATIONS</div>{NAV.map(([id,n,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?"nav active":"nav"}><Icon/><span>{n}</span><I.ChevronRight/></button>)}<div className="foot"><I.LockKeyhole/>AUTHORIZED ANALYSIS</div></aside>
<main><section className="hero"><div><div className="eyebrow"><i/>SIH 2026 • SMART AUTOMATION • SECURITY FABRIC</div><h1>Software supply chains,<br/><span>defended autonomously.</span></h1><p>OMEGA transforms an authorized repository into a continuously explainable security model: components, behavior, provenance, attack paths, evidence and approval-gated defense.</p><div className="chips"><b><I.BrainCircuit/>AI CORRELATION</b><b><I.RadioTower/>LIVE DETECTOR</b><b><I.Network/>ATTACK GRAPH</b><b><I.Bot/>DEFENSE LOOP</b></div></div><div className="reactor"><div className="core"><I.Crosshair/></div>{[1,2,3,4].map(x=><div className={"orb o"+x} key={x}/>)}</div></section>
<section className="upload" onClick={()=>ref.current?.click()}><input ref={ref} hidden type="file" accept=".zip" onChange={e=>scan(e.target.files?.[0])}/><I.UploadCloud/><div><b>{file?file.name:"DROP REPOSITORY ZIP INTO OMEGA"}</b><small>{file?"READY FOR FULL-SPECTRUM ANALYSIS":"ZIP only • local defensive scan • 50 MB demo limit"}</small></div><button onClick={e=>{e.stopPropagation();ref.current?.click()}}><I.Zap/> LAUNCH OMEGA SCAN</button></section>
{busy&&<Pipeline stage={stage} logs={logs}/>}
{!data&&!busy&&<Landing/>}
{data&&<Console data={data} tab={tab}/>}</main></div></div>}
function Pipeline({stage,logs}){return <section className="pipeline"><div className="pipehead"><b>OMEGA NEURAL PIPELINE</b><Badge k="green">● LIVE</Badge></div><div className="stages">{STAGES.map((s,i)=><div className={i<stage?"done":i===stage?"now":""} key={s}><strong>{i<stage?<I.CheckCircle2/>:i+1}</strong><small>{s}</small></div>)}</div><div className="terminal">{logs.slice(-6).map((x,i)=><div key={i}><span>›</span>{x}</div>)}</div></section>}
function Landing(){let cards=[["Live Detector","Watch security signals stream in real time.",I.RadioTower],["Threat Intelligence","Correlate findings into one risk picture.",I.Globe2],["Attack Path","Visualize the route from component to application.",I.Network],["Provenance & Trust","Expose trust assumptions and verification gaps.",I.Fingerprint],["CI/CD Guardian","Model pipeline policy gates before promotion.",I.GitPullRequest],["Risk Simulator","Explore how a finding changes posture.",I.SlidersHorizontal],["Evidence Vault","Create auditable, hashed evidence records.",I.Archive],["Compliance Matrix","Map security controls to observable evidence.",I.BadgeCheck],["AI Security Copilot","Explain findings, impact and next action.",I.BrainCircuit],["Defense Autopilot","Generate approval-gated response plans.",I.Bot],["Remediation Center","Prioritize fixes by blast radius.",I.Wrench],["SBOM Forge","Generate a component inventory.",I.FileJson]];return <section className="landing">{cards.map(([t,d,Icon])=><article key={t}><Icon/><b>{t}</b><p>{d}</p><small>MODULE READY <I.ChevronRight/></small></article>)}</section>}
function Console({data,tab}){return <section className="console"><Metrics d={data}/>{tab==="command"&&<Command d={data}/>} {tab==="live"&&<Live d={data}/>} {tab==="repo"&&<Repo d={data}/>} {tab==="deps"&&<Deps d={data}/>} {tab==="secrets"&&<Find d={data}cat="Secrets"t="SECRET SENTINEL"/>}{tab==="behavior"&&<Find d={data}cat="Behavior"t="BEHAVIOR LAB"/>}{tab==="intel"&&<Intel d={data}/>} {tab==="attack"&&<Attack d={data}/>} {tab==="trust"&&<Trust d={data}/>} {tab==="sbom"&&<SBOM d={data}/>} {tab==="cicd"&&<CICD d={data}/>} {tab==="risk"&&<Risk d={data}/>} {tab==="remediate"&&<Defense d={data}title="REMEDIATION CENTER"/>}{tab==="evidence"&&<Evidence d={data}/>} {tab==="compliance"&&<Compliance d={data}/>} {tab==="copilot"&&<Copilot d={data}/>} {tab==="defense"&&<Defense d={data}title="DEFENSE AUTOPILOT"/>}</section>}
function Metrics({d}){return <div className="metrics"><div className="score"><div className="dial" style={{"--p":d.security_score*3.6+"deg"}}><b>{d.security_score}</b><small>/100</small></div><div><small>SECURITY POSTURE</small><strong>{d.posture}</strong><p>Risk {d.risk_score}/100 • Scan {d.scan_id}</p></div></div>{[[d.summary.critical,"CRITICAL",I.AlertTriangle],[d.summary.high,"HIGH RISK",I.Activity],[d.summary.dependencies,"COMPONENTS",I.PackageSearch],[d.summary.files,"FILES",I.FileSearch]].map(([n,t,Icon])=><div className="metric" key={t}><Icon/><small>{t}</small><b>{n}</b></div>)}</div>}
function Head({k,t,d}){return <div className="head"><div><small>{k}</small><h2>{t}</h2><p>{d}</p></div><Badge k="green">● LIVE ANALYSIS</Badge></div>}
function Command({d}){return <><Head k="COMMAND CENTER"t="Autonomous threat picture"d="A unified view of repository posture, live signals and the defense loop."/><div className="quad"><Panel title="THREAT MATRIX">{[["Secrets",d.summary.critical],["Behavior",d.summary.high],["Dependencies",d.summary.medium],["Attack Surface",d.findings.length]].map(x=><div className="barrow" key={x[0]}><span>{x[0]}</span><div><i style={{width:Math.min(100,10+x[1]*18)+"%"}}/></div><b>{x[1]}</b></div>)}</Panel><Panel title="LIVE DEFENSE REACTOR"><div className="miniRadar"><I.Radar/><i/><i/><i/></div><b className="center">DETECT → ANALYZE → SCORE → DEFEND → VERIFY</b></Panel></div><Panel title="PRIORITY FINDINGS"><div className="finds">{d.findings.slice(0,8).map((f,i)=><Finding f={f}key={i}/>)}</div></Panel></>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Finding({f}){return <div className="finding"><i className={f.severity}/><div><b>{f.title}</b><small>{f.file}</small><p>{f.evidence}</p></div><Badge k={f.severity}>{f.severity.toUpperCase()}</Badge></div>}
function Live({d}){let[events,setEvents]=useState(d.live.events);useEffect(()=>{let t=setInterval(()=>setEvents(x=>[...x.slice(-7),d.live.events[Math.floor(Math.random()*d.live.events.length)]+" • "+Math.random().toString(16).slice(2,8)]),900);return()=>clearInterval(t)},[d]);return <><Head k="LIVE DETECTOR"t="Continuous signal stream"d="A visual simulation of the monitoring layer. Production mode can connect this feed to webhooks and event streams."/><div className="livegrid"><div className="signalOrb"><div><I.RadioTower/><b>LIVE</b></div></div><div className="stream">{events.map((e,i)=><div key={i}><span>{new Date().toLocaleTimeString()}</span><b>{e}</b><Badge k="green">OBSERVED</Badge></div>)}</div></div></>}
function Repo({d}){return <><Head k="REPOSITORY X-RAY"t="Topology intelligence"d="File inventory, technology signals and repository fingerprint."/><div className="cards">{[[d.summary.files,"FILES"],[(d.summary.bytes/1024).toFixed(1)+" KB","DATA"],[d.technology.join(" · ")||"UNKNOWN","STACK"],[d.scan_id,"FINGERPRINT"]].map(x=><div key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></div>)}</div><div className="extensions">{d.extensions.map(x=><span key={x[0]}>{x[0]}<b>{x[1]}</b></span>)}</div></>}
function Deps({d}){return <><Head k="DEPENDENCY DNA"t="Component intelligence"d="Extracted declarations with a trust baseline for further provenance verification."/><div className="table"><table><thead><tr><th>COMPONENT</th><th>VERSION</th><th>ECOSYSTEM</th><th>SCOPE</th><th>TRUST</th></tr></thead><tbody>{d.dependencies.map((x,i)=><tr key={i}><td><b>{x.name}</b></td><td>{x.version}</td><td>{x.ecosystem}</td><td>{x.scope}</td><td><span className="ok">● BASELINE</span></td></tr>)}</tbody></table></div></>}
function Find({d,cat,t}){let fs=d.findings.filter(x=>x.category===cat);return <><Head k="DEEP ANALYSIS"t={t}d="Evidence-based defensive heuristics. Uploaded source is never executed."/><Panel title={"SIGNALS • "+fs.length}>{fs.length?fs.map((f,i)=><Finding f={f}key={i}/>):<div className="empty"><I.CheckCircle2/><b>NO SIGNALS DETECTED</b></div>}</Panel></>}
function Intel({d}){return <><Head k="THREAT INTELLIGENCE"t="Correlation engine"d="Local signals are correlated into risk categories; external intelligence feeds are a production integration point."/><div className="intelgrid">{["VULNERABILITY CORRELATION","PACKAGE REPUTATION","BEHAVIOR SIGNALS","EXPLOITABILITY","BLAST RADIUS","POLICY IMPACT"].map((x,i)=><div key={x}><I.Globe2/><b>{x}</b><strong>{Math.min(99,58+d.risk_score+i*5)}%</strong><small>confidence model</small></div>)}</div></>}
function Attack({d}){return <><Head k="ATTACK PATH"t="Supply-chain exposure graph"d="Explainable path model: repository → components → signals → application/CI."/><div className="graph">{d.attack_graph.nodes.map((n,i)=><div className={"node "+n.kind} style={{left:(9+i*21)+"%",top:(i%2?63:23)+"%"}} key={n.id}><span>{i+1}</span><b>{n.label}</b><small>{n.kind}</small></div>)}{d.attack_graph.edges.map((e,i)=><div className="edge" key={i} style={{left:(15+i*19)+"%",top:"51%",transform:`rotate(${i%2?18:-18}deg)`}}/>)}</div></>}
function Trust({d}){return <><Head k="PROVENANCE & TRUST"t="Trust fabric"d="Make provenance assumptions explicit instead of treating every package as equally trusted."/><div className="trustgrid">{Object.entries(d.trust).map(([k,v])=><div key={k}><I.Fingerprint/><small>{k}</small><b>{v}</b><Badge k="yellow">REVIEW</Badge></div>)}</div></>}
function SBOM({d}){return <><Head k="SBOM FORGE"t="Machine-readable inventory"d="Deterministic local SBOM-style inventory ready for SPDX/CycloneDX adapters."/><pre className="json">{JSON.stringify(d.sbom,null,2)}</pre></>}
function CICD({d}){return <><Head k="CI/CD GUARDIAN"t="Pipeline policy gates"d="Model promotion decisions around repository risk and approval requirements."/><div className="gates">{["SOURCE INTEGRITY","DEPENDENCY POLICY","SECRET GATE","BUILD POLICY","SBOM GATE","APPROVAL GATE","DEPLOYMENT VERIFY"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><Badge k={i<d.summary.findings/2?"yellow":"green"}>{i<d.summary.findings/2?"REVIEW":"PASS"}</Badge></div>)}</div></>}
function Risk({d}){let[sev,setSev]=useState(2);let value=Math.max(0,Math.round(d.security_score-sev*9));return <><Head k="RISK SIMULATOR"t="What-if security model"d="Interactive scenario modeling. It does not alter the scanned repository."/><div className="sim"><div className="dial big" style={{"--p":value*3.6+"deg"}}><b>{value}</b><small>/100</small></div><input type="range"min="0"max="5"value={sev}onChange={e=>setSev(+e.target.value)}/><p>Simulated additional high-impact signals: <b>{sev}</b></p><div className="scenario"><b>DECISION</b><span>{value<50?"Escalate to incident response":"Maintain guarded posture and verify remediation"}</span></div></div></>}
function Defense({d,title}){return <><Head k="AUTONOMOUS DEFENSE"t={title}d="High-impact actions remain approval-gated and auditable."/><div className="loop">{["DETECT","ANALYZE","SCORE","RECOMMEND","APPROVE","VERIFY"].map((x,i)=><div className={i<4?"done":""}key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><Panel title="ACTION QUEUE">{d.defense_actions.length?d.defense_actions.map((a,i)=><div className="action"key={i}><I.Bot/><div><b>{a.action}</b><small>{a.target}</small></div><Badge k={a.mode==="approval-required"?"high":"green"}>{a.mode}</Badge></div>):<div className="empty">No remediation actions generated.</div>}</Panel></>}
function Evidence({d}){return <><Head k="EVIDENCE VAULT"t="Auditable evidence chain"d="Hashes and finding records make the scan reproducible without storing raw secret values."/><div className="evidence"><div><I.Fingerprint/><b>{d.sbom.sha256}</b><small>Repository SHA-256</small></div><div><I.Archive/><b>{d.scan_id}</b><small>Scan identifier</small></div><div><I.CheckCircle2/><b>{d.summary.findings}</b><small>Recorded findings</small></div></div></>}
function Compliance({d}){return <><Head k="COMPLIANCE MATRIX"t="Control coverage"d="A judge-friendly view of which security capabilities are observable in this prototype."/><div className="compliance">{Object.entries(d.compliance).map(([k,v])=><div key={k}><I.BadgeCheck/><b>{k}</b><Badge k={v==="mapped"?"green":"yellow"}>{v.toUpperCase()}</Badge><small>Evidence-backed module</small></div>)}</div></>}
function Copilot({d}){let top=d.findings[0];return <><Head k="AI SECURITY COPILOT"t="Explainable security reasoning"d="A deterministic copilot surface for the prototype; production can connect an approved enterprise LLM with retrieval and policy controls."/><div className="copilot"><div className="avatar"><I.BrainCircuit/></div><div><b>OMEGA ANALYST</b><p>{top?`Highest-priority signal: ${top.title} in ${top.file}. ${top.evidence} Recommended action: ${top.action}`:"No priority findings were produced by the current scan."}</p><div className="answers"><span>WHY IS THIS RISKY?</span><span>WHAT IS THE BLAST RADIUS?</span><span>WHAT SHOULD WE FIX FIRST?</span></div></div></div></>}
createRoot(document.getElementById("root")).render(<App/>);